- name: config_ops445
  hosts: cdcachero
  user: student
  become: yes
  vars:
    apache_version: 2.6
    motd_warning: "WARNING: used by ICT faculty/students only.\n"
    testserver: yes
  tasks:
    - name: update apache
      yum:
        name: httpd 
        state: latest

    - name: install EPEL release
      yum:      
        name: epel-release 
        state: present

    - name: remove 'tree' package
      yum:
        name: tree
        state: absent

    - name: set hostname to seneca id
      hostname:
        name: cdcachero

    - name: create new seneca user with sudo access
      user:
        name: cdcachero
        shell: /bin/bash
        groups: wheel
        create_home: yes

    - name: Configure ssh access for new user
      authorized_key:
        user: cdcachero
        state: present
        key: "{{ lookup('file', '/home/cdcachero/.ssh/id_rsa.pub') }}" 

    - name: Setup directory structure for labs
      file:
        path: "/home/cdcachero/ops445/lab{{item}}"
        state: directory
      loop: "{{ range(1, 10) | list }}"
