- name: config_ops445
  hosts: cdcachero
  user: student
  become: yes
  vars:
    apache_version: 2.6
    motd_warning: "WARNING: used by ICT faculty/students only.\n"
    testserver: yes
  tasks:
    - name: update apache
      yum:
        name: httpd 
        state: latest

    - name: install EPEL release
      yum:      
        name: epel-release 
        state: present
